#!/usr/bin/env python3
"""
Visualize Fortran field_map_*.bin files produced by the closed-cap concentrator code.

Expected binary format, written by export_field_map_binary:
  obs_x(:), obs_y(:), obs_z(:), e_sq(:)
all as float64, Fortran stream/unformatted, no header.

Typical files:
  results/260522_1530/field_map_xz.bin
  results/260522_1530/field_map_xy_z001.bin, ...

Examples:
  python3 visualize_result_bins.py --dir results/260522_1530
  python3 visualize_result_bins.py --latest
  python3 visualize_result_bins.py --dir results/260522_1530 --plot db
  python3 visualize_result_bins.py --dir results/260522_1530 --local-scale

Wall-excluded internal visualization:
  python3 visualize_result_bins.py --latest --plot both --exclude-wall --wall-radius 0.028 --wall-margin 0.90
"""

from __future__ import annotations

import argparse
import csv
import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

import numpy as np
import matplotlib.pyplot as plt


@dataclass
class FieldMap:
    path: Path
    kind: str                    # "XZ", "XY", or "UNKNOWN"
    npts: int
    nx: int
    ny_or_nz: int
    x: np.ndarray
    y: np.ndarray
    z: np.ndarray
    e2: np.ndarray
    X: np.ndarray
    Y_or_Z: np.ndarray
    E2: np.ndarray
    const_value: float           # y for XZ, z for XY
    e2_max: float
    e2_min_positive: float

    # position of maximum |E|^2 including all points
    e2_max_x: float
    e2_max_y: float
    e2_max_z: float


def natural_key(path: Path) -> Tuple:
    """Sort field_map_xy_z2.bin before field_map_xy_z10.bin."""
    parts = re.split(r"(\d+)", path.name)
    return tuple(int(p) if p.isdigit() else p for p in parts)


def finite_positive_max(arr: np.ndarray) -> float:
    vals = arr[np.isfinite(arr) & (arr > 0.0)]
    if vals.size == 0:
        return float("nan")
    return float(np.max(vals))


def finite_positive_min(arr: np.ndarray) -> float:
    vals = arr[np.isfinite(arr) & (arr > 0.0)]
    if vals.size == 0:
        return float("nan")
    return float(np.min(vals))


def finite_positive_argmax_position(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    e2: np.ndarray,
) -> Tuple[float, float, float, float]:
    """
    Return max(|E|^2) and its position x, y, z.
    Only finite and positive values are considered.
    """
    mask = np.isfinite(e2) & (e2 > 0.0)

    if not np.any(mask):
        return float("nan"), float("nan"), float("nan"), float("nan")

    idx_valid = np.where(mask)[0]
    idx_max = idx_valid[np.argmax(e2[mask])]

    return (
        float(e2[idx_max]),
        float(x[idx_max]),
        float(y[idx_max]),
        float(z[idx_max]),
    )


def masked_positive_max(arr: np.ndarray, mask: np.ndarray) -> float:
    vals = arr[mask & np.isfinite(arr) & (arr > 0.0)]
    if vals.size == 0:
        return float("nan")
    return float(np.max(vals))


def masked_argmax_position(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    e2: np.ndarray,
    mask: np.ndarray,
) -> Tuple[float, float, float, float]:
    valid = mask & np.isfinite(e2) & (e2 > 0.0)

    if not np.any(valid):
        return float("nan"), float("nan"), float("nan"), float("nan")

    idx_valid = np.where(valid)[0]
    idx_max = idx_valid[np.argmax(e2[valid])]

    return (
        float(e2[idx_max]),
        float(x[idx_max]),
        float(y[idx_max]),
        float(z[idx_max]),
    )


def unique_count(arr: np.ndarray, decimals: int = 12) -> Tuple[np.ndarray, int]:
    """
    Coordinates are generated by arithmetic loops, so unique values should be exact.
    Rounding is added only to avoid tiny floating noise if the binary format changes later.
    """
    vals = np.unique(np.round(arr[np.isfinite(arr)], decimals=decimals))
    return vals, vals.size


def read_field_map_binary(path: Path) -> FieldMap:
    raw = np.fromfile(path, dtype=np.float64)

    if raw.size == 0:
        raise ValueError(f"empty file: {path}")

    if raw.size % 4 != 0:
        raise ValueError(
            f"{path}: data length {raw.size} is not divisible by 4. "
            "Expected x,y,z,e2 arrays as float64."
        )

    npts = raw.size // 4
    x = raw[0:npts]
    y = raw[npts:2 * npts]
    z = raw[2 * npts:3 * npts]
    e2 = raw[3 * npts:4 * npts]

    ux, nx = unique_count(x)
    uy, ny = unique_count(y)
    uz, nz = unique_count(z)

    e2_max, e2_max_x, e2_max_y, e2_max_z = finite_positive_argmax_position(
        x, y, z, e2
    )
    e2_min_positive = finite_positive_min(e2)

    # XZ map: y is constant, x and z vary.
    # x is inner loop, z is outer loop.
    if ny == 1 and nx * nz == npts:
        X = x.reshape((nz, nx))
        Z = z.reshape((nz, nx))
        E2 = e2.reshape((nz, nx))

        return FieldMap(
            path=path,
            kind="XZ",
            npts=npts,
            nx=nx,
            ny_or_nz=nz,
            x=x,
            y=y,
            z=z,
            e2=e2,
            X=X,
            Y_or_Z=Z,
            E2=E2,
            const_value=float(uy[0]),
            e2_max=e2_max,
            e2_min_positive=e2_min_positive,
            e2_max_x=e2_max_x,
            e2_max_y=e2_max_y,
            e2_max_z=e2_max_z,
        )

    # XY map: z is constant, x and y vary.
    # x is inner loop, y is outer loop.
    if nz == 1 and nx * ny == npts:
        X = x.reshape((ny, nx))
        Y = y.reshape((ny, nx))
        E2 = e2.reshape((ny, nx))

        return FieldMap(
            path=path,
            kind="XY",
            npts=npts,
            nx=nx,
            ny_or_nz=ny,
            x=x,
            y=y,
            z=z,
            e2=e2,
            X=X,
            Y_or_Z=Y,
            E2=E2,
            const_value=float(uz[0]),
            e2_max=e2_max,
            e2_min_positive=e2_min_positive,
            e2_max_x=e2_max_x,
            e2_max_y=e2_max_y,
            e2_max_z=e2_max_z,
        )

    raise ValueError(
        f"{path}: could not infer grid. "
        f"unique counts: nx={nx}, ny={ny}, nz={nz}, npts={npts}."
    )


def internal_mask_for_max(
    fmap: FieldMap,
    wall_radius: float,
    wall_margin: float,
) -> np.ndarray:
    """
    Return mask for internal points, excluding near-wall region.

    For XY map:
        r = sqrt(x^2 + y^2)

    For XZ map:
        y is constant, usually y = 0, so radial distance on the displayed
        section is approximated by abs(x).

    This mask is used only for deciding color scale and displayed maximum.
    The original field data are not modified.
    """
    if wall_radius <= 0.0:
        return np.isfinite(fmap.e2) & (fmap.e2 > 0.0)

    r_limit = wall_margin * wall_radius

    if fmap.kind == "XY":
        r = np.sqrt(fmap.x**2 + fmap.y**2)
        mask = r < r_limit

    elif fmap.kind == "XZ":
        r = np.abs(fmap.x)
        mask = r < r_limit

    else:
        mask = np.ones_like(fmap.e2, dtype=bool)

    mask &= np.isfinite(fmap.e2)
    mask &= fmap.e2 > 0.0

    return mask


def find_latest_results_dir(root: Path) -> Path:
    candidates = []

    if not root.exists():
        raise FileNotFoundError(f"results root not found: {root}")

    for p in root.iterdir():
        if not p.is_dir():
            continue
        if any(p.glob("field_map*.bin")):
            candidates.append(p)

    if not candidates:
        raise FileNotFoundError(
            f"no result directories with field_map*.bin under {root}"
        )

    # Prefer timestamp-like directory names, otherwise modified time.
    timestamp_like = [p for p in candidates if re.match(r"^\d{6}_\d{4}$", p.name)]

    if timestamp_like:
        return sorted(timestamp_like, key=lambda q: q.name)[-1]

    return sorted(candidates, key=lambda q: q.stat().st_mtime)[-1]


def collect_bin_files(result_dir: Path) -> List[Path]:
    files = sorted(result_dir.glob("field_map*.bin"), key=natural_key)

    if not files:
        raise FileNotFoundError(f"no field_map*.bin files found in {result_dir}")

    return files


def to_db(E2: np.ndarray, ref: float, floor_db: float) -> np.ndarray:
    out = np.full_like(E2, np.nan, dtype=np.float64)

    mask = (
        np.isfinite(E2)
        & (E2 > 0.0)
        & np.isfinite(ref)
        & (ref > 0.0)
    )

    out[mask] = 10.0 * np.log10(E2[mask] / ref)
    out = np.maximum(out, floor_db)

    return out


def normalized_linear(E2: np.ndarray, ref: float) -> np.ndarray:
    out = np.full_like(E2, np.nan, dtype=np.float64)

    mask = np.isfinite(E2) & np.isfinite(ref) & (ref > 0.0)
    out[mask] = E2[mask] / ref

    return out

def color_limits_excluding_peak(
    C: np.ndarray,
    mode: str,
    exclude_peak: bool = False,
    percentile: Optional[float] = None,
    db_floor: float = -60.0,
) -> Tuple[Optional[float], Optional[float]]:
    """
    Decide color limits without changing the plotted data.

    exclude_peak:
        Trueなら最大値1点をカラースケール決定から除く。

    percentile:
        例: 99.0なら上位1%を飽和させる。
        干渉縞を見るなら 95, 99 あたりが便利。
    """
    vals = C[np.isfinite(C)]

    if vals.size == 0:
        return None, None

    vals_for_scale = vals.copy()

    if exclude_peak and vals_for_scale.size >= 2:
        imax = np.argmax(vals_for_scale)
        vals_for_scale = np.delete(vals_for_scale, imax)

    if percentile is not None:
        vmax = float(np.nanpercentile(vals_for_scale, percentile))
    else:
        vmax = float(np.nanmax(vals_for_scale))

    if mode == "db":
        vmin = db_floor
    else:
        vmin = 0.0

    if not np.isfinite(vmax) or vmax <= vmin:
        vmax = float(np.nanmax(vals))

    return vmin, vmax


def plot_one_map(
    fmap: FieldMap,
    out_path: Path,
    mode: str,
    ref: float,
    cmap: str,
    db_floor: float,
    dpi: int,
    file_format: str,
    peak_e2: Optional[float] = None,
    peak_x: Optional[float] = None,
    peak_y: Optional[float] = None,
    peak_z: Optional[float] = None,
    peak_label: str = "max",
    exclude_peak_from_colormap: bool = False,
    color_percentile: Optional[float] = None,
) -> None:
    if mode == "db":
        C = to_db(fmap.E2, ref=ref, floor_db=db_floor)
        label = r"$10\log_{10}(|E|^2/|E|^2_{\mathrm{ref}})$ [dB]"

        vmin, vmax = color_limits_excluding_peak(
            C,
            mode="db",
            exclude_peak=exclude_peak_from_colormap,
            percentile=color_percentile,
            db_floor=db_floor,
        )

    elif mode == "linear":
        C = normalized_linear(fmap.E2, ref=ref)
        label = r"$|E|^2/|E|^2_{\mathrm{ref}}$ [-]"

        vmin, vmax = color_limits_excluding_peak(
            C,
            mode="linear",
            exclude_peak=exclude_peak_from_colormap,
            percentile=color_percentile,
            db_floor=db_floor,
        )

    elif mode == "raw":
        C = fmap.E2
        label = r"$|E|^2$"

        vmin, vmax = color_limits_excluding_peak(
            C,
            mode="raw",
            exclude_peak=exclude_peak_from_colormap,
            percentile=color_percentile,
            db_floor=db_floor,
        )

    else:
        raise ValueError(f"unknown mode: {mode}")

    if peak_e2 is None:
        peak_e2 = fmap.e2_max
        peak_x = fmap.e2_max_x
        peak_y = fmap.e2_max_y
        peak_z = fmap.e2_max_z

    fig, ax = plt.subplots(figsize=(7.2, 5.8))

    im = ax.pcolormesh(
        fmap.X,
        fmap.Y_or_Z,
        C,
        shading="auto",
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
    )

    cb = fig.colorbar(im, ax=ax)
    cb.set_label(label)

    # Show maximum point on the image.
    if (
        peak_e2 is not None
        and peak_x is not None
        and peak_y is not None
        and peak_z is not None
        and np.isfinite(peak_e2)
        and np.isfinite(peak_x)
        and np.isfinite(peak_y)
        and np.isfinite(peak_z)
    ):
        if fmap.kind == "XZ":
            x_peak = peak_x
            y_peak = peak_z
            coord_text = (
                rf"{peak_label} $|E|^2$ = {peak_e2:.3e}" "\n"
                rf"$x$ = {peak_x:.4e} m" "\n"
                rf"$z$ = {peak_z:.4e} m"
            )

        elif fmap.kind == "XY":
            x_peak = peak_x
            y_peak = peak_y
            coord_text = (
                rf"{peak_label} $|E|^2$ = {peak_e2:.3e}" "\n"
                rf"$x$ = {peak_x:.4e} m" "\n"
                rf"$y$ = {peak_y:.4e} m"
            )

        else:
            x_peak = peak_x
            y_peak = peak_y
            coord_text = rf"{peak_label} $|E|^2$ = {peak_e2:.3e}"

        # White circle + black cross, because rainbow colormap is visually noisy.
        ax.plot(
            x_peak,
            y_peak,
            marker="o",
            markersize=12,
            markerfacecolor="none",
            markeredgecolor="white",
            markeredgewidth=2.0,
        )

        ax.plot(
            x_peak,
            y_peak,
            marker="x",
            markersize=10,
            markeredgewidth=2.0,
            color="black",
        )

        ax.text(
            0.02,
            0.98,
            coord_text,
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=9,
            bbox=dict(
                boxstyle="round",
                facecolor="white",
                alpha=0.75,
                edgecolor="black",
            ),
        )

    if fmap.kind == "XZ":
        ax.set_xlabel("x [m]")
        ax.set_ylabel("z [m]")
        ax.set_title(f"{fmap.path.name}  XZ plane, y={fmap.const_value:.4g} m")
        ax.set_aspect("equal", adjustable="box")

    elif fmap.kind == "XY":
        ax.set_xlabel("x [m]")
        ax.set_ylabel("y [m]")
        ax.set_title(f"{fmap.path.name}  XY plane, z={fmap.const_value:.6g} m")
        ax.set_aspect("equal", adjustable="box")

    else:
        ax.set_xlabel("x [m]")
        ax.set_ylabel("coordinate [m]")
        ax.set_title(fmap.path.name)

    ax.grid(False)
    fig.tight_layout()
    fig.savefig(out_path.with_suffix(f".{file_format}"), dpi=dpi)
    plt.close(fig)


def plot_xy_peak_vs_z(
    maps: Sequence[FieldMap],
    out_dir: Path,
    file_format: str,
    dpi: int,
    exclude_wall: bool,
    wall_radius: float,
    wall_margin: float,
) -> None:
    xy_maps = [m for m in maps if m.kind == "XY"]

    if len(xy_maps) < 2:
        return

    xy_maps = sorted(xy_maps, key=lambda m: m.const_value)

    z_list = []
    peak_list = []

    for m in xy_maps:
        if exclude_wall:
            mask = internal_mask_for_max(
                m,
                wall_radius=wall_radius,
                wall_margin=wall_margin,
            )
            peak = masked_positive_max(m.e2, mask)
        else:
            peak = m.e2_max

        if np.isfinite(peak):
            z_list.append(m.const_value)
            peak_list.append(peak)

    if len(z_list) < 2:
        return

    z = np.array(z_list, dtype=float)
    peak = np.array(peak_list, dtype=float)
    peak_norm = peak / np.nanmax(peak)

    fig, ax = plt.subplots(figsize=(7.2, 4.6))
    ax.plot(z, peak_norm, marker="o")
    ax.set_xlabel("z [m]")

    if exclude_wall:
        ax.set_ylabel(r"internal peak $|E|^2$ normalized [-]")
        ax.set_title("Internal peak intensity along XY planes")
    else:
        ax.set_ylabel(r"peak $|E|^2$ normalized [-]")
        ax.set_title("Peak intensity along XY planes")

    ax.grid(True)
    fig.tight_layout()
    fig.savefig(out_dir / f"xy_peak_vs_z.{file_format}", dpi=dpi)
    plt.close(fig)


def write_summary_csv(
    maps: Sequence[FieldMap],
    out_dir: Path,
    exclude_wall: bool,
    wall_radius: float,
    wall_margin: float,
) -> None:
    csv_path = out_dir / "field_map_summary.csv"

    with csv_path.open("w", newline="") as f:
        writer = csv.writer(f)

        writer.writerow([
            "file",
            "kind",
            "npts",
            "nx",
            "ny_or_nz",
            "const_y_or_z_m",
            "x_min_m",
            "x_max_m",
            "y_min_m",
            "y_max_m",
            "z_min_m",
            "z_max_m",
            "e2_max_all",
            "e2_max_all_x_m",
            "e2_max_all_y_m",
            "e2_max_all_z_m",
            "e2_max_internal",
            "e2_max_internal_x_m",
            "e2_max_internal_y_m",
            "e2_max_internal_z_m",
            "e2_min_positive",
        ])

        for m in maps:
            if exclude_wall:
                mask = internal_mask_for_max(
                    m,
                    wall_radius=wall_radius,
                    wall_margin=wall_margin,
                )

                (
                    e2_max_internal,
                    e2_max_internal_x,
                    e2_max_internal_y,
                    e2_max_internal_z,
                ) = masked_argmax_position(m.x, m.y, m.z, m.e2, mask)

            else:
                e2_max_internal = float("nan")
                e2_max_internal_x = float("nan")
                e2_max_internal_y = float("nan")
                e2_max_internal_z = float("nan")

            writer.writerow([
                m.path.name,
                m.kind,
                m.npts,
                m.nx,
                m.ny_or_nz,
                f"{m.const_value:.12e}",
                f"{np.nanmin(m.x):.12e}",
                f"{np.nanmax(m.x):.12e}",
                f"{np.nanmin(m.y):.12e}",
                f"{np.nanmax(m.y):.12e}",
                f"{np.nanmin(m.z):.12e}",
                f"{np.nanmax(m.z):.12e}",
                f"{m.e2_max:.12e}",
                f"{m.e2_max_x:.12e}",
                f"{m.e2_max_y:.12e}",
                f"{m.e2_max_z:.12e}",
                f"{e2_max_internal:.12e}",
                f"{e2_max_internal_x:.12e}",
                f"{e2_max_internal_y:.12e}",
                f"{e2_max_internal_z:.12e}",
                f"{m.e2_min_positive:.12e}",
            ])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualize results/<timestamp>/field_map*.bin files."
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--dir",
        type=Path,
        help="result directory, e.g. results/260522_1530",
    )
    group.add_argument(
        "--latest",
        action="store_true",
        help="use latest timestamp-like directory under --root",
    )

    parser.add_argument(
        "--root",
        type=Path,
        default=Path("results"),
        help="root results directory for --latest",
    )

    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output directory for figures",
    )

    parser.add_argument(
        "--plot",
        choices=["db", "linear", "raw", "both", "all"],
        default="both",
    )

    parser.add_argument(
        "--global-scale",
        dest="global_scale",
        action="store_true",
        default=True,
        help="use one reference max for all maps, default",
    )

    parser.add_argument(
        "--local-scale",
        dest="global_scale",
        action="store_false",
        help="normalize each file by its own maximum",
    )

    parser.add_argument(
        "--db-floor",
        type=float,
        default=-60.0,
        help="minimum dB value shown",
    )

    parser.add_argument(
        "--cmap",
        default="rainbow",
        help="matplotlib colormap name",
    )

    parser.add_argument(
        "--format",
        default="svg",
        choices=["svg", "png", "pdf"],
        help="figure file format",
    )

    parser.add_argument(
        "--dpi",
        type=int,
        default=200,
        help="DPI for png/pdf output",
    )

    parser.add_argument(
        "--exclude-wall",
        action="store_true",
        help="exclude near-wall points when computing max/ref values",
    )

    parser.add_argument(
        "--wall-radius",
        type=float,
        default=0.0280,
        help="pipe/concentrator wall radius used for wall exclusion [m]",
    )

    parser.add_argument(
        "--wall-margin",
        type=float,
        default=0.90,
        help="use points with r < wall_margin * wall_radius as internal points",
    )
    parser.add_argument(
        "--exclude-peak-from-colormap",
        action="store_true",
        help="exclude the single largest plotted value when deciding color scale",
    )

    parser.add_argument(
        "--color-percentile",
        type=float,
        default=None,
        help="use this percentile as color-scale maximum, e.g. 99 or 95",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.dir is not None:
        result_dir = args.dir
    else:
        result_dir = find_latest_results_dir(args.root)

    if not result_dir.exists():
        raise FileNotFoundError(f"result directory not found: {result_dir}")

    out_dir = args.out if args.out is not None else result_dir / "bin_visualization"
    out_dir.mkdir(parents=True, exist_ok=True)

    files = collect_bin_files(result_dir)

    print(f"Result directory : {result_dir}")
    print(f"Output directory : {out_dir}")
    print(f"Found {len(files)} binary field map files")

    maps: List[FieldMap] = []

    for path in files:
        fmap = read_field_map_binary(path)
        maps.append(fmap)

        print(
            f"  {path.name}: {fmap.kind}, grid={fmap.nx} x {fmap.ny_or_nz}, "
            f"max_all(|E|^2)={fmap.e2_max:.6e}, "
            f"at x={fmap.e2_max_x:.6e} m, "
            f"y={fmap.e2_max_y:.6e} m, "
            f"z={fmap.e2_max_z:.6e} m"
        )

    # Decide reference value for global-scale plots.
    # If --exclude-wall is used, the reference is computed from internal points only.
    if args.exclude_wall:
        internal_refs = []

        for m in maps:
            mask = internal_mask_for_max(
                m,
                wall_radius=args.wall_radius,
                wall_margin=args.wall_margin,
            )
            val = masked_positive_max(m.e2, mask)

            if np.isfinite(val) and val > 0.0:
                internal_refs.append(val)

        if len(internal_refs) == 0:
            raise ValueError(
                "No valid internal points were found. "
                "Check --wall-radius and --wall-margin."
            )

        global_ref = float(np.max(internal_refs))

        print("")
        print("Wall exclusion is enabled:")
        print(f"  wall_radius = {args.wall_radius:.6e} m")
        print(f"  wall_margin = {args.wall_margin:.6e}")
        print(
            f"  internal radius limit = "
            f"{args.wall_radius * args.wall_margin:.6e} m"
        )
        print(f"  global internal reference |E|^2 = {global_ref:.12e}")

    else:
        global_ref = finite_positive_max(np.concatenate([m.e2 for m in maps]))

    if not np.isfinite(global_ref) or global_ref <= 0.0:
        raise ValueError("all |E|^2 values are NaN or non-positive; nothing to plot")

    # Print global maximum.
    if args.exclude_wall:
        best = None
        best_tuple = None

        for m in maps:
            mask = internal_mask_for_max(
                m,
                wall_radius=args.wall_radius,
                wall_margin=args.wall_margin,
            )
            current = masked_argmax_position(m.x, m.y, m.z, m.e2, mask)

            if not np.isfinite(current[0]):
                continue

            if best is None or current[0] > best:
                best = current[0]
                best_tuple = (m, current)

        if best_tuple is not None:
            best_map, current = best_tuple
            print("")
            print("Global internal maximum over all field maps:")
            print(
                f"  file = {best_map.path.name}, "
                f"kind = {best_map.kind}, "
                f"max_internal(|E|^2) = {current[0]:.12e}, "
                f"x = {current[1]:.12e} m, "
                f"y = {current[2]:.12e} m, "
                f"z = {current[3]:.12e} m"
            )

    else:
        global_max_map = max(
            maps,
            key=lambda m: m.e2_max if np.isfinite(m.e2_max) else -np.inf,
        )

        print("")
        print("Global maximum over all field maps:")
        print(
            f"  file = {global_max_map.path.name}, "
            f"kind = {global_max_map.kind}, "
            f"max_all(|E|^2) = {global_max_map.e2_max:.12e}, "
            f"x = {global_max_map.e2_max_x:.12e} m, "
            f"y = {global_max_map.e2_max_y:.12e} m, "
            f"z = {global_max_map.e2_max_z:.12e} m"
        )

    print("")

    if args.plot == "both":
        modes = ["db", "linear"]
    elif args.plot == "all":
        modes = ["db", "linear", "raw"]
    else:
        modes = [args.plot]

    for fmap in maps:
        if args.exclude_wall:
            mask = internal_mask_for_max(
                fmap,
                wall_radius=args.wall_radius,
                wall_margin=args.wall_margin,
            )

            peak_e2, peak_x, peak_y, peak_z = masked_argmax_position(
                fmap.x,
                fmap.y,
                fmap.z,
                fmap.e2,
                mask,
            )

            peak_label = "internal max"

        else:
            peak_e2 = fmap.e2_max
            peak_x = fmap.e2_max_x
            peak_y = fmap.e2_max_y
            peak_z = fmap.e2_max_z
            peak_label = "max"

        for mode in modes:
            if mode in ("db", "linear"):
                if args.global_scale:
                    ref = global_ref
                    scale_tag = "global_internal" if args.exclude_wall else "global"
                else:
                    if args.exclude_wall:
                        ref = peak_e2
                        scale_tag = "local_internal"
                    else:
                        ref = fmap.e2_max
                        scale_tag = "local"
            else:
                ref = fmap.e2_max
                scale_tag = "raw"

            stem = f"{fmap.path.stem}_{mode}_{scale_tag}"

            plot_one_map(
                fmap=fmap,
                out_path=out_dir / stem,
                mode=mode,
                ref=ref,
                cmap=args.cmap,
                db_floor=args.db_floor,
                dpi=args.dpi,
                file_format=args.format,
                peak_e2=peak_e2,
                peak_x=peak_x,
                peak_y=peak_y,
                peak_z=peak_z,
                peak_label=peak_label,
                exclude_peak_from_colormap=args.exclude_peak_from_colormap,
                color_percentile=args.color_percentile,
            )

    plot_xy_peak_vs_z(
        maps,
        out_dir=out_dir,
        file_format=args.format,
        dpi=args.dpi,
        exclude_wall=args.exclude_wall,
        wall_radius=args.wall_radius,
        wall_margin=args.wall_margin,
    )

    write_summary_csv(
        maps,
        out_dir=out_dir,
        exclude_wall=args.exclude_wall,
        wall_radius=args.wall_radius,
        wall_margin=args.wall_margin,
    )

    print("Done.")
    print(f"Figures and summary were saved in: {out_dir}")


if __name__ == "__main__":
    main()